import { d365ArchitectureEvolution, d365Video } from "./d365VideoStory.js";

export const projectsData = [
  {
    id: "d365-finance-operations-replication",
    domain: "de",
    viz: "pipeline",
    tagline: "Three serverless pipelines redesigned as two job-compute workflows — with 90% lower compute cost.",
    title: "D365 Finance & Operations Real-Time Data Replication",
    description: "A D365-to-Databricks replication redesign that removed an ADLS copy layer, reduced three pipelines to two, and cut compute cost by 90%.",
    logo: "/logos/dynamics365-finance-operations.svg",
    architecture: null,
    fullDescription:
      "Redesigned the replication path from Dynamics 365 Finance & Operations to Power BI. The original architecture exported CSV files every 30 minutes, converted them to Parquet, copied them between two ADLS locations, registered external tables, copied those into managed tables, and then applied CDC into Delta Live Tables. The optimized design keeps the reliable Synapse Link export but ingests the CSV files directly into Databricks managed Delta tables. A second workflow performs CDC and DLT processing for Power BI. Removing one pipeline, one storage-copy layer, and repeated serverless execution reduced compute cost by 90% and made the platform easier to operate and recover.",
    tech: ["D365 Finance", "Synapse Link", "Databricks Jobs", "Delta Live Tables", "Power BI"],
    technologies: ["Dynamics 365 Finance & Operations", "Azure Synapse Link", "Azure Data Lake Storage Gen2", "Databricks Job Compute", "Managed Delta Tables", "Delta Live Tables", "Change Data Capture", "PySpark", "Power BI"],
    image: "/logos/dynamics365-finance-operations.svg",
    metrics: [
      { label: "Pipeline Count", value: "3 → 2", description: "One orchestration boundary removed" },
      { label: "Compute Cost", value: "−90%", description: "Job compute replaced serverless execution" },
      { label: "Source Export", value: "30 min", description: "Synapse Link CSV cadence retained" },
      { label: "Copy Layers", value: "−1", description: "No CSV-to-Parquet cross-ADLS hop" },
    ],
    problem:
      "The original design moved each 30-minute D365 CSV export through three serverless pipelines: CSV-to-Parquet plus an ADLS-to-ADLS copy, external-to-managed table loading, and CDC into DLT tables. The repeated copies and compute startups increased end-to-end processing time, cost, operational complexity, and the number of places a recovery could fail.",
    solution:
      "We kept Synapse Link as the D365 export contract, then removed the intermediate Parquet conversion, second ADLS location, and external-table handoff. Databricks job compute now ingests landing-zone CSV files directly into managed Delta tables. A second workflow applies CDC into DLT tables and serves Power BI. The shorter path reduced the design from three pipelines to two and lowered compute cost by 90%.",
    architectureEvolution: d365ArchitectureEvolution,
    video: d365Video,
    optimizations: [
      "Removed the CSV-to-Parquet conversion and the copy between two ADLS locations.",
      "Loaded Synapse Link CSV files directly into Databricks managed Delta tables.",
      "Reduced orchestration from three pipelines to two workflows, removing one full pipeline.",
      "Replaced repeated serverless execution with right-sized Databricks job compute.",
      "Kept CDC and DLT processing isolated from ingestion so each workflow has one responsibility.",
    ],
    features: [
      "Synapse Link CSV exports retained at the existing 30-minute source cadence",
      "Direct CSV-to-managed-Delta ingestion from the landing ADLS location",
      "CDC processing from managed tables into Delta Live Tables",
      "Two job-compute workflows with clear ingestion and transformation ownership",
      "Serverless compute replaced with Databricks job compute",
      "Power BI consumption preserved while the upstream architecture was simplified",
    ],
    challenges:
      "To confirm the optimized path preserved the same data, I ran validation across the existing and redesigned flows. The checks covered schema compatibility, file completeness for late or duplicate files, incremental watermark boundaries, idempotent reruns, row-count reconciliation, and CDC parity. The results confirmed that data remained consistent from the source through the managed and DLT layers.",
    duration: "6 months",
    role: "Lead Data Engineer",
    team: "4 engineers",
    status: "Completed - In Active Production",
    liveUrl: null,
    githubUrl: null,
  },
  {
    id: "databricks-disaster-recovery",
    domain: "de",
    viz: "failover",
    tagline: "Zero-data-loss failover between Databricks workspaces, orchestrated end to end.",
    title: "Databricks Disaster Recovery Setup",
    description: "Enterprise-grade disaster recovery solution using Databricks Delta Sharing and DeepClone for data replication and failover",
    logo: "/Images/projects/DR/disaster-recovery-icon.jpg",
    fullDescription:
      "Designed and implemented a comprehensive disaster recovery (DR) architecture for Databricks workspaces using Delta Sharing, DeepClone, and CLI-based health monitoring. The solution ensures continuous data replication from primary to secondary workspace, enables seamless failover when the primary workspace is unavailable, and automatically resumes normal operations upon recovery. This multi-step process maintains data integrity, minimizes downtime, and provides proactive monitoring of both environments.",
    tech: ["Databricks", "Delta Sharing", "DeepClone", "CLI", "Python"],
    technologies: ["Databricks", "Delta Lake", "Delta Sharing", "DeepClone", "Python CLI", "Fabric", "SQL"],
    image: "https://via.placeholder.com/300x200?text=Databricks+DR",
    metrics: [
      { label: "Uptime", value: "99.9%", description: "Continuous availability" },
      { label: "RPO", value: "<1 hour", description: "Recovery Point Objective" },
      { label: "RTO", value: "30 mins", description: "Recovery Time Objective" },
      { label: "Data Loss", value: "Zero", description: "Zero data loss verified" },
    ],
    problem:
      "Organizations running critical analytics on Databricks needed a robust disaster recovery solution to ensure business continuity. The challenge was designing a system that could continuously replicate data from primary to secondary workspace, automatically detect failures, seamlessly failover workloads, and restore normal operations—all while maintaining zero data loss and minimal downtime.",
    solution:
      "We implemented a four-phase orchestration system: (1) Data Replication - Delta Sharing securely shares primary data with automatic DeepClone copying into secondary catalogs, (2) Failover Activation - CLI monitors detect primary unavailability and pause replication while resuming secondary workflows, (3) Primary Recovery - Reverse DeepClone syncs changes back to primary with data consistency checks, (4) Normal Operations - Resume regular replication schedule with continuous health monitoring. This multi-step process ensures business continuity with automated failover and recovery.",
    features: [
      "Real-time data replication via Delta Sharing from primary to secondary workspace",
      "DeepClone workflows creating independent, consistent datasets every 6 hours",
      "CLI-based health monitoring for primary workspace availability and performance",
      "Automated failover activation when primary workspace becomes unavailable",
      "Reverse sync capabilities to restore data consistency after primary recovery",
      "Fabric shortcut automation for seamless reporting and dashboard failover",
      "Multi-step orchestration ensuring zero data loss and minimal downtime",
    ],
    challenges:
      "Ensuring data consistency across primary and secondary workspaces during replication, preventing conflicts during failover and recovery, and orchestrating complex multi-step workflows. We solved these by implementing DeepClone for independent data copies, using Delta Sharing for secure read-only access, and building a sophisticated CLI monitor with state management to orchestrate the entire DR lifecycle.",
    duration: "4 months",
    role: "Data Architect & Engineer",
    team: "4 engineers",
    status: "Completed",
    liveUrl: null,
    githubUrl: null,
    steps: [
      {
        title: "Step 1: Data Replication from Primary to Secondary Workspace",
        description:
          "Ensure all critical data from the primary Databricks workspace is continuously available in the secondary workspace for disaster recovery purposes, while monitoring the health of the primary environment.",
        details: [
          "Primary Workspace Workflows: All workflows continue running normally in the primary workspace",
          "Delta Sharing: Data from primary catalogs is shared with the secondary Databricks workspace via Delta Sharing, allowing secure, real-time access to primary data without full duplication",
          "DeepClone Workflows: In the secondary workspace, DeepClone workflows copy the Delta-shared tables into secondary catalogs, creating independent, consistent datasets",
          "CLI Health Monitor: A CLI-based monitor continuously checks the health of the primary Databricks workspace, verifying availability of critical clusters and workflows, and triggering alerts on failures",
        ],
        keyPoints: [
          "Delta Sharing ensures secure, read-only access to primary data without impacting production workloads",
          "DeepClone workflows guarantee full data integrity in the secondary workspace",
          "CLI Health Monitor provides real-time visibility into primary workspace health",
        ],
        image: "/Images/projects/DR/Items.png",
      },
      {
        title: "Step 2: Failover Activation",
        description:
          "Ensure business continuity by switching all workloads to the secondary Databricks workspace when the primary workspace is unavailable.",
        details: [
          "CLI Health Monitor continuously checks the primary workspace health",
          "Failover Trigger: When the CLI monitor detects that the primary workspace is down, failover is initiated",
          "Delta Sharing from Primary → Secondary is stopped to prevent data inconsistencies",
          "DeepClone workflows in the secondary workspace are paused to avoid conflicts during failover",
          "Other workflows in the secondary workspace are resumed, allowing secondary to take over active processing",
          "Fabric shortcuts are altered via APIs through the CLI monitor to reflect failover changes in reports and dashboards",
        ],
        keyPoints: [
          "Ensures minimal downtime by switching operations to the secondary workspace",
          "Protects data integrity by pausing replication jobs and stopping delta sharing",
          "Secondary workspace becomes fully operational until the primary is restored",
        ],
        image: "/Images/projects/DR/Items-2.png",
      },
      {
        title: "Step 3: Primary Recovery and Reverse Sync",
        description:
          "Safely resume operations in the primary workspace once it becomes available, ensuring data consistency with the secondary workspace.",
        details: [
          "CLI Health Monitor detects that the primary workspace is back online",
          "Workflows in the secondary workspace are paused to prevent data conflicts",
          "Reverse DeepClone jobs are initiated from the secondary workspace back to the primary catalogs, ensuring all changes made during failover are synchronized",
          "Once reverse DeepClone jobs complete successfully, the primary workspace resumes normal workflows",
          "Data replication resumes from the primary workspace to secondary catalogs via Delta Sharing",
        ],
        keyPoints: [
          "Guarantees data consistency by synchronizing any updates made in the secondary workspace back to the primary",
          "Prevents conflicts and ensures smooth transition of workloads back to primary",
          "CLI monitor ensures the primary is fully healthy before resuming its workflows",
        ],
        image: "/Images/projects/DR/Items-3.png",
      },
      {
        title: "Step 4: Normal Operations and Ongoing Replication",
        description:
          "Restore the disaster recovery architecture to its normal state, ensuring continuous replication and data availability between primary and secondary workspaces.",
        details: [
          "Delta Sharing from the primary workspace to secondary workspace is resumed",
          "DeepClone workflows in the secondary workspace are restarted on their regular schedule (every 6 hours) to maintain updated copies of primary catalogs",
          "All workflows in the primary workspace continue running as normal",
          "Fabric shortcuts are switched back to point to the primary workspace storage account, ensuring all reports and dashboards reflect the primary environment",
          "CLI Health Monitor continues to monitor both workspaces, ensuring early detection of any issues",
        ],
        keyPoints: [
          "Ensures continuous data replication and disaster recovery readiness",
          "Maintains data integrity and consistency between primary and secondary workspaces",
          "Ensures reporting accuracy by switching Fabric shortcuts back to the primary storage",
          "Provides proactive monitoring to detect potential failures before they impact operations",
        ],
        image: "/Images/projects/DR/Items-4.png",
      },
    ],
  },

  {
    id: "synapse-databricks-migration",
    domain: "de",
    viz: "migration",
    tagline: "Lifting data and pipelines off Azure Synapse onto Databricks — outputs unchanged.",
    title: "Synapse → Databricks Migration",
    tech: ["Azure Databricks", "Azure Synapse", "Synapse Link", "Delta Lake", "PySpark"],
    technologies: ["Azure Databricks", "Azure Synapse Analytics", "Synapse Link", "SQL Server", "Delta Lake", "PySpark"],
    description:
      "D365 data landed into SQL Server through Synapse pipelines via Synapse Link. I re-platformed the whole ingestion and transformation layer — moving both the data and the pipelines from Synapse onto Azure Databricks.",
    fullDescription:
      "The existing stack pulled Dynamics 365 data into SQL Server using Azure Synapse pipelines fed by Synapse Link. To consolidate on the lakehouse, I migrated the historical data into Delta Lake and rebuilt the Synapse pipelines as Databricks workflows, validating that downstream outputs matched before cutover.",
    features: [
      "Migrated historical D365 / SQL Server data into Delta Lake on Databricks.",
      "Rebuilt Synapse pipelines as native Databricks workflows.",
      "Validated row-level parity between old and new outputs before cutover.",
      "Consolidated ingestion on the lakehouse to cut platform sprawl.",
    ],
    role: "Data Engineer",
    status: "Completed",
    liveUrl: null,
    githubUrl: null,
  },
  {
    id: "d365-data-retention",
    domain: "de",
    viz: "retention",
    tagline: "Retaining Dynamics 365 records in Databricks before D365 purges them.",
    title: "D365 Data Retention",
    tech: ["Azure Databricks", "Delta Lake", "D365", "PySpark"],
    technologies: ["Azure Databricks", "Delta Lake", "Dynamics 365 (BYOD)", "PySpark", "Azure Data Lake"],
    description:
      "Dynamics 365 purges historical BYOD data on a retention schedule. I built a Databricks solution that captures and retains that data in Delta Lake before it is deleted — preserving full history for analytics and audit.",
    fullDescription:
      "D365 enforces retention limits that delete older records, which breaks long-range reporting and audit. I architected an Azure Databricks solution that captures BYOD data ahead of its scheduled purge and retains it in Delta Lake, so analytics and compliance queries keep working against history D365 no longer holds.",
    features: [
      "Captures D365 BYOD data ahead of its scheduled deletion.",
      "Retains full history in Delta Lake with schema tracking.",
      "Keeps analytics and audit queries working on purged records.",
      "Runs as a scheduled, incremental capture with checkpointing.",
    ],
    role: "Data Engineer",
    status: "Completed",
    liveUrl: null,
    githubUrl: null,
  },
  {
    id: "synapse-fabric-link",
    domain: "de",
    viz: "links",
    tagline: "Synapse Link and Fabric Link wired up with fallback so ingestion survives failures.",
    title: "Synapse Link & Fabric Link Integration",
    tech: ["Azure Synapse Link", "Microsoft Fabric", "D365", "Delta Lake"],
    technologies: ["Azure Synapse Link", "Microsoft Fabric Link", "Dynamics 365", "Azure Data Lake", "Delta Lake"],
    description:
      "Configured Azure Synapse Link and Microsoft Fabric Link to continuously surface D365 data into the lake, with fallback logic so ingestion continues seamlessly when one path fails.",
    fullDescription:
      "To keep D365 data flowing into the lakehouse without single points of failure, I set up Azure Synapse Link and Microsoft Fabric Link as parallel ingestion paths and added fallback logic that switches paths automatically during outages — keeping data fresh even when a connector degrades.",
    features: [
      "Set up Synapse Link for CDC export of D365 data.",
      "Set up Fabric Link as a parallel ingestion path.",
      "Fallback logic switches paths automatically during failures.",
      "Continuous, seamless ingestion with no manual intervention.",
    ],
    role: "Data Engineer",
    status: "Completed",
    liveUrl: null,
    githubUrl: null,
  },
  {
    id: "operational-db-warehouse",
    domain: "de",
    viz: "opdb",
    tagline: "APIs to a SQL Server operational store, modeled into a Synapse star-schema warehouse.",
    title: "Operational Database & Data Warehouse",
    tech: ["Azure Synapse", "Dataflows", "SQL Server", "Star Schema", "Python"],
    technologies: ["Azure Synapse Analytics", "Synapse Dataflows", "SQL Server", "Star Schema", "Python", "T-SQL"],
    description:
      "Built the operational data layer end to end — ingesting from source APIs into a SQL Server operational database, then loading and modeling it into a dimensional warehouse using Azure Synapse dataflows.",
    fullDescription:
      "I stood up the data foundation for the business: ingestion jobs pulled data from source APIs into a SQL Server operational database, and Azure Synapse dataflows moved and reshaped it into a star-schema data warehouse. That dimensional model became the single source for all downstream Power BI reporting.",
    features: [
      "API ingestion jobs landing source data into a SQL Server operational store.",
      "Synapse dataflows moving data from the operational DB into the warehouse.",
      "Star-schema model (facts + conformed dimensions) for analytics.",
      "Incremental loading with indexing and partitioning for fast refreshes.",
    ],
    role: "Data Engineer",
    status: "Completed",
    liveUrl: null,
    githubUrl: null,
  },
  {
    id: "databricks-cicd-dab",
    domain: "de",
    viz: "cicd",
    tagline: "CI/CD for Databricks with Asset Bundles across dev, test, and prod workspaces.",
    title: "Databricks CI/CD with Asset Bundles",
    tech: ["Databricks Asset Bundles", "Azure DevOps", "CI/CD", "Databricks"],
    technologies: ["Databricks Asset Bundles (DABs)", "Azure DevOps", "CI/CD", "Databricks Workflows", "YAML"],
    description:
      "Set up Databricks Asset Bundles and separate dev, test, and prod workspaces, giving Lindsay a repeatable, config-as-code promotion path for jobs and pipelines.",
    fullDescription:
      "To make deployments reliable at Lindsay, I defined jobs, pipelines, and configuration as code using Databricks Asset Bundles (DABs) and established isolated dev, test, and prod workspaces. Changes now promote through environments in a repeatable, reviewable way instead of being hand-copied between workspaces.",
    features: [
      "Databricks Asset Bundles defining jobs, pipelines, and configs as code.",
      "Isolated dev / test / prod workspaces with environment-specific settings.",
      "Repeatable promotion from development through to production.",
      "Version-controlled deployments replacing manual workspace changes.",
    ],
    role: "Sr. Databricks Data Engineer",
    status: "In production",
    liveUrl: null,
    githubUrl: null,
  },
  {
    id: "powerbi-reporting-suite",
    domain: "da",
    viz: "powerbi",
    tagline: "Seven Power BI dashboards on a star-schema warehouse — from shelf life to out-of-stock.",
    title: "Power BI Reporting Suite",
    tech: ["Power BI", "DAX", "SQL Server", "Star Schema"],
    technologies: ["Power BI", "DAX", "Power Query", "SQL Server", "Star Schema", "Row-Level Security"],
    description:
      "Built a suite of seven Power BI dashboards on the star-schema warehouse, giving field reps and managers operational visibility across the product lifecycle.",
    fullDescription:
      "On top of the SQL Server star-schema warehouse, I built a connected suite of seven Power BI dashboards covering the retail-operations lifecycle — shelf life, rep activity, stock health, quality, merchandising compliance, and exceptions — with DAX measures and drill-down for self-serve analysis.",
    metrics: [{ label: "Dashboards", value: "7", description: "on one star schema" }],
    features: [
      "Code Date — product shelf-life tracking.",
      "Rep Store Visits — field-rep store-visit activity.",
      "Low Stock & Out of Stock — inventory gaps by store.",
      "Quality & Credits — quality issues and credit tracking.",
      "Planogram — shelf / merchandising compliance.",
      "Missing Tags — shelf-tag gaps.",
      "Hot Tags & Error Items — priority and exception items.",
    ],
    role: "Data Analyst / BI Developer",
    status: "Completed",
    liveUrl: null,
    githubUrl: null,
  },
  {
    id: "lindsay-enterprise-dashboards",
    domain: "da",
    viz: "dashboards",
    tagline: "Sales, supplier, and IT-operations dashboards for leadership at Lindsay.",
    title: "Enterprise Dashboards — Lindsay",
    tech: ["Databricks AI/BI", "Power BI", "DAX", "SQL"],
    technologies: ["Databricks AI/BI Dashboards", "Power BI", "DAX", "SQL", "Unity Catalog"],
    description:
      "Built interactive executive dashboards at Lindsay covering sales performance, supplier metrics, and IT operational KPIs.",
    fullDescription:
      "At Lindsay I built a set of leadership-facing dashboards on Databricks AI/BI and Power BI — turning refined Gold-layer data into decision-ready views of sales performance, supplier metrics, and IT operations.",
    features: [
      "Sales dashboard — revenue and order performance.",
      "Supplier dashboards — supplier performance and metrics.",
      "IT metrics dashboards — operational and IT KPIs.",
      "Built on governed Gold-layer data via Unity Catalog.",
    ],
    role: "Sr. Databricks Data Engineer",
    status: "In production",
    liveUrl: null,
    githubUrl: null,
  },
  {
    id: "crop-yield-forecasting",
    domain: "ai",
    viz: "cropyield",
    tagline: "Forecasting crop yield from satellite, soil, and weather signals with an ML ensemble.",
    title: "Crop Yield Forecasting",
    tech: ["Python", "Scikit-learn", "XGBoost", "Pandas", "Feature Engineering"],
    technologies: ["Python", "Scikit-learn", "XGBoost", "Random Forest", "Pandas", "NumPy", "Matplotlib"],
    description:
      "A machine-learning model that forecasts crop yield by fusing vegetation, soil, and weather signals into a single feature set — giving an early, field-level estimate of output.",
    fullDescription:
      "Crop yield depends on signals no single source captures. This model fuses satellite vegetation indices (NDVI / EVI), soil properties, and seasonal weather into one feature space, then trains an ensemble (Random Forest / XGBoost) on historical yield. Feature-importance analysis surfaces the strongest drivers, and predictions are evaluated against actual yield using R² and RMSE.",
    features: [
      "Fuses satellite vegetation indices, soil properties, and weather into one feature set.",
      "Ensemble model (Random Forest / XGBoost) trained on historical yield.",
      "Feature-importance analysis to surface the strongest yield drivers.",
      "Evaluated with predicted-vs-actual, R², and RMSE.",
    ],
    role: "Data Scientist",
    status: "Completed",
    note: "Architecture reflects the standard approach — confirm your exact inputs, model, and metrics.",
    liveUrl: null,
    githubUrl: null,
  },
  {
    id: "demand-forecasting",
    domain: "ai",
    viz: "demand",
    tagline: "Predicting per-product demand from point-of-sale and shipped-sales history.",
    title: "Demand Forecasting",
    tech: ["Python", "Scikit-learn", "Time Series", "Pandas"],
    technologies: ["Python", "Scikit-learn", "Time Series", "Pandas", "PySpark", "Azure Databricks"],
    description:
      "A two-signal demand model that learns from both point-of-sale and shipped-sales history, then predicts upcoming demand per product to guide planning.",
    fullDescription:
      "Demand shows up differently in what sells at the register and what ships to stores. This model trains on both point-of-sale and shipped-sales history to predict product-level demand, feeding upstream planning so supply is staged ahead of orders.",
    metrics: [{ label: "Forecast accuracy", value: "+15%", description: "vs. prior baseline" }],
    features: [
      "Combines point-of-sale and shipped-sales signals as training inputs.",
      "ML models trained to predict product-level demand.",
      "Forecasts feed planning for upcoming sales orders.",
      "Built with data scientists and business teams on cross-functional delivery.",
    ],
    role: "Data Engineer / Data Analyst",
    status: "Completed",
    liveUrl: null,
    githubUrl: null,
  },
];

/* Domain metadata drives the section grouping + accent colours. */
export const domains = [
  {
    key: "de",
    label: "Data Engineering",
    accent: "var(--color-signal)",
    hex: "#3fe0ff",
    blurb: "Pipelines that move fast, never drop a row, and cost less every quarter.",
  },
  {
    key: "da",
    label: "Data Analytics",
    accent: "var(--color-amber)",
    hex: "#ffb43d",
    blurb: "Turning the warehouse into dashboards and experiments people act on.",
  },
  {
    key: "ai",
    label: "AI / Machine Learning",
    accent: "var(--color-violet)",
    hex: "#b492ff",
    blurb: "Models in production — forecasting, NLP, and deep learning that ships.",
  },
];
